- platform: mqtt
  name: Spa Lock
  unique_id: binary_sensor.spa_lock
  state_topic: "layzspa/message"
  value_template: |- #"{{ value_json.LCK }}"
    {% if value_json.LCK == 1 %}
      ON
    {% else %}
      OFF
    {% endif %}
  expire_after: 700
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  device_class: lock

- platform: mqtt
  name: Spa Heater Element
  unique_id: binary_sensor.spa_heater_element
  state_topic: "layzspa/message"
  value_template: |- #"{{ value_json.RED }}"
    {% if value_json.RED == 1 %}
      ON
    {% else %}
      OFF
    {% endif %}
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700
  device_class: heat

- platform: mqtt
  name: Spa Ready
  unique_id: binary_sensor.spa_ready
  state_topic: "layzspa/message"
  value_template: |- #"{{ value_json.RED }}"
    {% if value_json.TMP > 30 %}
      {% if value_json.TMP >= value_json.TGT-1 %}
        ON
      {% else %}
        OFF
      {% endif %}

    {% else %}
      OFF
    {% endif %}
  icon: mdi:hot-tub
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700

- platform: mqtt 
  name: Spa Status
  unique_id: binary_sensor.spa_status
  device_class: connectivity
  entity_category: diagnostic
  state_topic: "layzspa/Status" 
  availability_topic: "layzspa/Status"
  payload_available: "Alive" 
  payload_not_available: "Dead"
  payload_on: "Alive" 
  payload_off: "Dead"

  # 4 Wire Error State based on character display [E00]
- platform: mqtt 
  name: Spa Error
  unqiue_id: binary_sensor.spa_error
  device_class: problem
  entity_category: diagnostic
  state_topic: "layzspa/message"
  value_template: "{{ value_json.CH1 }}"
  availability_topic: "layzspa/Status"
  payload_available: "Alive" 
  payload_not_available: "Dead"
  payload_on: 69 
  payload_off: 32
