- platform: mqtt
  name: spa lock
  state_topic: "layzspa/message"
  value_template: |- #"{{ value_json.LCK }}"
    {% if value_json.LCK == 1 %}
      ON
    {% else %}
      OFF
    {% endif %}
  expire_after: 700
  icon: mdi:lock
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  device_class: lock

- platform: mqtt
  name: spa heater element
  state_topic: "layzspa/message"
  value_template: |- #"{{ value_json.RED }}"
    {% if value_json.RED == 1 %}
      ON
    {% else %}
      OFF
    {% endif %}
  icon: mdi:fire
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700

- platform: mqtt
  name: spa ready
  state_topic: "layzspa/message"
  value_template: |- #"{{ value_json.RED }}"
    {% if value_json.TMP > 30 %}
      {% if value_json.TMP >= value_json.TGT-1 %}
        ON
      {% else %}
        OFF
      {% endif %}

    {% else %}
      OFF
    {% endif %}
  icon: mdi:hot-tub
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700

- platform: mqtt 
  name: Spa Status
  device_class: connectivity
  entity_category: diagnostic
  state_topic: "layzspa/Status" 
  availability_topic: "layzspa/Status"
  payload_available: "Alive" 
  payload_not_available: "Dead"
  payload_on: "Alive" 
  payload_off: "Dead"
