- platform: mqtt
  name: Spa Button
  unique_id: sensor.spa_button
  state_topic: "layzspa/button"
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"

- platform: mqtt
  name: Spa Connect Count
  unique_id: sensor.spa_connect_count
  state_topic: "layzspa/MQTT_Connect_Count"

- platform: mqtt
  name: Spa Temperature
  unique_id: sensor.spa_temperature
  state_topic: "layzspa/message"
  unit_of_measurement: '°C'
  value_template: "{{ value_json.TMP }}"
  expire_after: 700
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"

- platform: mqtt
  name: Spa Target Temperature
  unique_id: sensor.spa_target_temperature
  unit_of_measurement: '°C'
  state_topic: "layzspa/message"
  value_template: "{{ value_json.TGT }}"
  expire_after: 700

- platform: mqtt
  name: Spa Time to Target
  unique_id: sensor.spa_time_to_target
  icon: mdi:clock
  unit_of_measurement: 'hours'
  state_topic: "layzspa/times"
  value_template: "{{ (value_json.TTTT / 3600 | float) | round(2) }}"
  expire_after: 700

- platform: mqtt
  name: Spa Energy
  unique_id: sensor.spa_energy
  device_class: energy
  state_class: total_increasing
  unit_of_measurement: kWh
  icon: mdi:flash
  state_topic: "layzspa/times"
  value_template: "{{ value_json.KWH }}"
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700

- platform: mqtt
  name: Spa CL Added
  unique_id: sensor.spa_cl_added
  unit_of_measurement: days
  icon: hass:hand-coin-outline
  state_topic: "layzspa/times"
  value_template: "{{ ( ( (now().timestamp()|int) - value_json.CLTIME|int)/3600/24) | round(2) }}"
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700

- platform: mqtt
  name: Spa Filter Changed
  unique_id: sensor.spa_filter_changed
  unit_of_measurement: days
  icon: hass:air-filter
  state_topic: "layzspa/times"
  value_template: "{{ ( ( (now().timestamp()|int) - value_json.FTIME|int)/3600/24) | round(2) }}"
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700
