- platform: mqtt
  name: spa button
  state_topic: "BW_2.0.0/button"
  availability_topic: "BW_2.0.0/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"

- platform: mqtt
  name: spa connect count
  state_topic: "BW_2.0.0/MQTT_Connect_Count"

- platform: mqtt
  name: spa temperature
  state_topic: "BW_2.0.0/message"
  unit_of_measurement: '°C'
  value_template: "{{ value_json.TMP }}"
  expire_after: 700
  availability_topic: "BW_2.0.0/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"

- platform: mqtt
  name: spa target temperature
  unit_of_measurement: '°C'
  state_topic: "BW_2.0.0/message"
  value_template: "{{ value_json.TGT }}"
  expire_after: 700

- platform: mqtt
  name: spa time to target
  unit_of_measurement: 'hours'
  state_topic: "BW_2.0.0/times"
  value_template: "{{ (value_json.TTTT / 3600 | float) | round(2) }}"
  expire_after: 700

- platform: mqtt
  name: spa energy
  device_class: energy
  state_class: total_increasing
  unit_of_measurement: kWh
  icon: mdi:flash
  state_topic: "BW_2.0.0/times"
  value_template: "{{ value_json.KWH }}"
  availability_topic: "BW_2.0.0/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700

- platform: mqtt
  name: spa cl added
  unit_of_measurement: days
  icon: hass:hand-coin-outline
  state_topic: "BW_2.0.0/times"
  value_template: "{{ ( ( (now().timestamp()|int) - value_json.CLTIME|int)/3600/24) | round(2) }}"
  availability_topic: "BW_2.0.0/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700

- platform: mqtt
  name: spa filter changed
  unit_of_measurement: days
  icon: hass:air-filter
  state_topic: "BW_2.0.0/times"
  value_template: "{{ ( ( (now().timestamp()|int) - value_json.FTIME|int)/3600/24) | round(2) }}"
  availability_topic: "BW_2.0.0/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"
  expire_after: 700