- platform: mqtt
  name: spa heat regulation
  command_topic: "layzspa/command"
  state_topic: "layzspa/message"
  value_template: |-
    {% if value_json.RED == 1 %}
      1
    {% elif value_json.GRN == 1 %}
      1
    {% else %}
      0
    {% endif %}
  icon: mdi:radiator
  state_on: 1
  state_off: 0
  payload_on: '{CMD:3,VALUE:true,XTIME:0,INTERVAL:0}'
  payload_off: '{CMD:3,VALUE:false,XTIME:0,INTERVAL:0}'
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"

- platform: mqtt
  name: spa airbubbles
  command_topic: "layzspa/command"
  state_topic: "layzspa/message"
  value_template: "{{ value_json.AIR }}"
  icon: mdi:chart-bubble
  payload_on: '{CMD:2,VALUE:true,XTIME:0,INTERVAL:0}'
  payload_off: '{CMD:2,VALUE:false,XTIME:0,INTERVAL:0}'
  state_on: 1
  state_off: 0
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"

- platform: mqtt
  name: spa pump
  command_topic: "layzspa/command"
  state_topic: "layzspa/message"
  value_template: "{{ value_json.FLT }}"
  icon: mdi:pump
  payload_on: '{CMD:4,VALUE:true,XTIME:0,INTERVAL:0}'
  payload_off: '{CMD:4,VALUE:false,XTIME:0,INTERVAL:0}'
  state_on: 1
  state_off: 0
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"

- platform: mqtt
  name: spa temperature unit
  command_topic: "layzspa/command"
  state_topic: "layzspa/message"
  value_template: "{{ value_json.UNT }}"
  icon: mdi:temperature-celsius
  payload_on: '{CMD:1,VALUE:true,XTIME:0,INTERVAL:0}'
  payload_off: '{CMD:1,VALUE:false,XTIME:0,INTERVAL:0}'
  state_on: 1
  state_off: 0
  availability_topic: "layzspa/Status"
  payload_available: "Alive"
  payload_not_available: "Dead"